[versions]
kotlin = "2.1.0"
compose = "1.7.0"
junit = "5.11.0"
intellij-platform-gradle-plugin = "2.1.0"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
intellij-platform = { id = "org.jetbrains.intellij.platform", version.ref = "intellij-platform-gradle-plugin" }
intellij-platform-settings = { id = "org.jetbrains.intellij.platform.settings", version.ref = "intellij-platform-gradle-plugin" }
